In [1]:
import tensorflow as tf

In [2]:
dense_units = 5
vocab_size = 100
embedding_dim = 3
max_length = 6      # no of timesteps
gru_units = 10     # same for encoder and decoder, enc/dec size
batch_size = 3

In [3]:
# Input shape = (batch_size, max_length)
inputs = tf.Variable([
                [2, 3, 4, 10, 43, 8], # eg: <start> this is a  bag <end>
                [4, 30, 23, 33,54, 28],   #eg: <start> he is a boy <end>
                [6, 8, 47, 54, 76, 45] # eg: <start> this is a bird <end>
                     ])

In [4]:
print(f"Inputs: \n{inputs.numpy()}")

Inputs: 
[[ 2  3  4 10 43  8]
 [ 4 30 23 33 54 28]
 [ 6  8 47 54 76 45]]


In [5]:
print(f"Input Shape: {inputs.shape}")

Input Shape: (3, 6)


In [6]:
enc_embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
x = enc_embedding(inputs)

In [7]:
print(f"Embeddings: \n{x}")

Embeddings: 
[[[-0.00132639  0.01883603 -0.01345297]
  [-0.00391147 -0.0347651   0.04811133]
  [ 0.04871162 -0.01824908 -0.01515586]
  [ 0.02356746 -0.04965495 -0.00068355]
  [-0.03167943 -0.02627767 -0.03221848]
  [-0.02731177 -0.00763317  0.01325849]]

 [[ 0.04871162 -0.01824908 -0.01515586]
  [ 0.02538553  0.0477307   0.02858791]
  [ 0.00514483 -0.0317423  -0.03415427]
  [-0.04468792  0.04590322 -0.04994699]
  [-0.00261893 -0.01745418 -0.02205311]
  [ 0.01370437  0.02946173 -0.01830461]]

 [[-0.0283754  -0.00784552  0.04486674]
  [-0.02731177 -0.00763317  0.01325849]
  [-0.01411619 -0.00993254 -0.04445205]
  [-0.00261893 -0.01745418 -0.02205311]
  [ 0.03152374  0.01547927  0.00967903]
  [ 0.01175907  0.02556838 -0.00720749]]]


In [8]:
# Embedding Shape = (batch_size, max_length)
print(f"Embedding Shape: {x.shape}")

Embedding Shape: (3, 6, 3)


In [9]:
# Encoder GRU
enc_gru = tf.keras.layers.GRU(gru_units,
                               return_sequences=True,
                               return_state=True,
                               recurrent_initializer='glorot_uniform')

In [10]:
# output_shape = (batch_size, max_length, hidden_size_encoder)
enc_output, enc_hidden = enc_gru(x)

In [11]:
print(f"Output of Encoder or Values: {enc_output.shape}")
print(f"State of Encoder: {enc_hidden.shape}")

Output of Encoder or Values: (3, 6, 10)
State of Encoder: (3, 10)


In [12]:
values = enc_output

In [13]:
# Query shape = (batch_size, gru_units)
query = enc_hidden
print(f"Query Shape: {query.shape}")

Query Shape: (3, 10)


In [14]:
# Query with time axis shape = (batch_size, 1, gru_units)
query_with_time_axis = tf.expand_dims(query, 1)
print(f"Query with Time Axis Shape: {query_with_time_axis.shape}")

Query with Time Axis Shape: (3, 1, 10)


In [15]:
#Attention Layers
query_layer = tf.keras.layers.Dense(dense_units)
value_layer = tf.keras.layers.Dense(dense_units)
V = tf.keras.layers.Dense(1)

In [16]:
# intermediate query shape = (batch_size, 1, dense_units)
intermediate_query = query_layer(query_with_time_axis)
print(f"Intermediate Query Shape: {intermediate_query.shape}")

Intermediate Query Shape: (3, 1, 5)


In [17]:
# intermediate values shape = (batch_size, max_length, dense_units)
intermediate_values = value_layer(values)
print(f"Intermediate Values Shape: {intermediate_values.shape}")

Intermediate Values Shape: (3, 6, 5)


In [18]:
# without V shape = (batch_size, max_length, dense_units)
without_v = tf.tanh(intermediate_query + intermediate_values)
print(f"Without V layer: {without_v.shape}")

Without V layer: (3, 6, 5)


In [19]:
# score shape = (batch_size, max_length, 1) #applying V
score = V(tf.nn.tanh(
    query_layer(query_with_time_axis) + value_layer(values)))
print(f"Score Shape: {score.shape}")

Score Shape: (3, 6, 1)


In [20]:
attention_weights = tf.nn.softmax(score, axis=1)
print(f"Attention Weights Shape: {attention_weights.shape}")

Attention Weights Shape: (3, 6, 1)


In [21]:
context_vector = attention_weights * values
context_vector = tf.reduce_sum(context_vector, axis=1)
print(f"Context Vector Shape: {context_vector.shape}")

Context Vector Shape: (3, 10)


In [22]:
# Decoder Embedding
dec_embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)

In [23]:
# Decoder GRU
dec_gru = tf.keras.layers.GRU(gru_units,
                               return_sequences=True,
                               return_state=True,
                               recurrent_initializer='glorot_uniform')


In [24]:
# Decoder Fully Connected
fc = tf.keras.layers.Dense(vocab_size)

In [25]:
 # loss object
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')

In [26]:
# Loss Function
def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss_ = loss_object(real, pred)
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    return tf.reduce_mean(loss_)

In [27]:
# Decoder Inputs
decoder_inputs = tf.Variable([
    [1, 2, 3], #eg. <start> adfk <end>
    [2, 4, 6], #eg. <start> rtrtt <end>
    [4, 8, 5]  #eg. <start> jadskf <end>
])


In [28]:
for i in range(3):
    print("\n\n\n")
    single_dec_input = tf.expand_dims(decoder_inputs[:, i], 1)
    print(f"Decoder Input Shape {single_dec_input.shape}")
    # y shape after passing through embedding == (batch_size, 1, embedding_dim)
    y = dec_embedding(single_dec_input)
    print(f"Decoder Embedding Shape: {y.shape}")
    # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)
    y = tf.concat([tf.expand_dims(context_vector, 1), y], axis=-1)
    print(f"After Context Vector Concatenation Shape: {y.shape}")
    # passing the concatenated vector to the GRU
    output, state = dec_gru(y)
    print(f"Decoder GRU Output Shape: {output.shape}")
    # output shape == (batch_size * 1, hidden_size)
    output = tf.reshape(output, (-1, output.shape[2]))
    print(f"Decoder GRU Output Shape Reshape: {output.shape}")
    # output shape == (batch_size, vocab)
    y = fc(output)
    print(f"Fully Connected Output: {y.shape}")
    # print(y)
    loss = loss_function(real=decoder_inputs[:, i], pred=y)
    print(loss)






Decoder Input Shape (3, 1)
Decoder Embedding Shape: (3, 1, 3)
After Context Vector Concatenation Shape: (3, 1, 13)
Decoder GRU Output Shape: (3, 1, 10)
Decoder GRU Output Shape Reshape: (3, 10)
Fully Connected Output: (3, 100)
tf.Tensor(4.604135, shape=(), dtype=float32)




Decoder Input Shape (3, 1)
Decoder Embedding Shape: (3, 1, 3)
After Context Vector Concatenation Shape: (3, 1, 13)
Decoder GRU Output Shape: (3, 1, 10)
Decoder GRU Output Shape Reshape: (3, 10)
Fully Connected Output: (3, 100)
tf.Tensor(4.605104, shape=(), dtype=float32)




Decoder Input Shape (3, 1)
Decoder Embedding Shape: (3, 1, 3)
After Context Vector Concatenation Shape: (3, 1, 13)
Decoder GRU Output Shape: (3, 1, 10)
Decoder GRU Output Shape Reshape: (3, 10)
Fully Connected Output: (3, 100)
tf.Tensor(4.607655, shape=(), dtype=float32)
